# Sometimes scripts call bash instead of my beloved zsh
# ...so I have to maintain a little bashrc too I guess

# Use what I can
source ~/.local/zsh/platform.zsh
source ~/.local/zsh/path.zsh
source ~/.local/zsh/env.zsh
source ~/.local/zsh/aliases.zsh
source ~/.local/zsh/functions.zsh

# umask permissions
umask 0002

