# Sometimes scripts call bash instead of my beloved zsh
# ...so I have to maintain a little bashrc too I guess

# Use what I can
source ~/.local/zsh/platform.zsh
source ~/.local/zsh/path.zsh
source ~/.local/zsh/env.zsh
source ~/.local/zsh/aliases.zsh
source ~/.local/zsh/functions.zsh

# http://direnv.net
! command -v direnv >/dev/null 2>&1 || { 
  eval "$(direnv hook bash)" 
}

# umask permissions
umask 0002

