#!/bin/sh

# 2014 Jon Suderman
# https://github.com/suderman/local/

# Open a terminal and run this command:
# curl local.suderman.io/install | sh

# Ensure git & git-clone-pull exists
curl -sS git-clone-pull.suderman.io/install | sh

# Git clone/pull this repo to the home directory
git clone-pull https://github.com/suderman/local.git ~/.local

# Ask before installing private repo on this computer
read -p "Do you want to install ~/.local/secret on this computer? (y/[n]) " -n 1 -r
echo
[[ $REPLY =~ ^[Yy]$ ]]
if [ ! $? -ne 0 ]; then

  # Secret repo contains SSH and other sensitive config
  git clone-pull https://github.com/suderman/secret.git ~/.local/secret

  # Update remote origins to use SSH
  cd ~/.local && git remote set-url origin git@github.com:suderman/local.git
  cd ~/.local/secret && git remote set-url origin git@github.com:suderman/secret.git
fi

# Install rcm to manage the dotfiles
curl -sS install.suderman.io/rcm | sh

# Ensure the .rcrc file exists before rcup is run at all
ln -sf ~/.local/dotfiles/rcrc ~/.rcrc
rcup

echo "...done!"
