#!/bin/sh

brew update
brew upgrade

# homebrew taps
brew tap homebrew/dupes
brew tap homebrew/versions
brew tap homebrew/homebrew-php
brew tap thoughtbot/formulae
brew tap suderman/suds
brew tap phinze/cask 
brew tap caskroom/versions 
brew tap caskroom/fonts

# homebrew external commands
osx brew-cask                       || brew install brew-cask

# dependencies
osx Xcode.app                       || app xcode/id497799835
osx XQuartz.app                     || brew cask install xquartz
osx cscope                          || brew install cscope
osx /usr/local/bin/ctags            || brew install ctags-exuberant

# languages
osx node                            || brew cask install node
osx lua                             || brew install lua
osx luajit                          || brew install luajit
osx /usr/local/bin/python           || brew install python
osx /usr/local/bin/php              || brew install php55 --with-mysql --with-cgi
osx /usr/local/bin/ruby             || brew install ruby
osx chruby-exec                     || brew install chruby
osx ruby-install                    || brew install ruby-install
osx nginx                           || brew install nginx

# databases
osx redis-server                    || brew install redis
osx mongod                          || brew install mongodb
osx mysql                           || brew install mysql
osx Sequel Pro.app                  || brew cask install sequel-pro  

# git
osx /usr/local/bin/git              || brew install git
osx tig                             || brew install tig
osx gitsh                           || brew install gitsh
osx Gitbox.app                      || brew cask install gitbox

# shell
osx iTerm.app                       || brew cask install iterm2
osx tmux                            || brew install tmux
osx wemux                           || brew install wemux
osx rcup                            || brew install rcm
osx direnv                          || brew install direnv
osx mosh                            || brew install mobile-shell

# shell apps
osx mackup                          || brew install mackup
osx ssh-copy-id                     || brew install ssh-copy-id
osx autojump                        || brew install autojump
osx ranger                          || brew install ranger
osx highlight                       || brew install highlight
osx wget                            || brew install wget
osx dockutil                        || brew install dockutil
osx fswatch                         || brew install fswatch
osx duti                            || brew install duti

# virtual machine
osx VMware Fusion.app               || brew cask install vmware-fusion
osx VirtualBox.app                  || brew cask install virtualbox
osx vagrant                         || brew cask install vagrant
osx docker                          || brew install docker
osx packer                          || brew install packer
osx ec2-describe-regions            || brew install ec2-api-tools

# dev apps
osx fzf                             || brew install fzf
osx ack                             || brew install ack
osx ag                              || brew install ag
osx /usr/local/bin/vim              || brew install vim --with-client-server --with-lua --with-luajit
osx heroku                          || brew cask install heroku-toolbelt
osx Kaleidoscope.app                || brew cask install kaleidoscope
osx convert                         || brew install imagemagick --build-from-source
osx fontforge                       || brew install fontforge
osx Transmit.app                    || brew cask install transmit
osx Integrity.app                   || brew cask install integrity
osx MockSMTP.app                    || app mocksmtp/id423535515          

# browsers
osx FirefoxDeveloperEdition.app     || brew cask install firefoxdeveloperedition
osx Google Chrome.app               || brew cask install google-chrome
osx Fluid.app                       || brew cask install fluid
osx Choosy.prefPane                 || brew cask install choosy
osx Flash Player.app                || brew cask install flash-player
osx Silverlight.plugin              || brew cask install silverlight
osx w3m                             || brew install w3m

# files
osx owncloud.app                    || brew cask install owncloud
osx BitTorrent Sync.app             || brew cask install bittorrent-sync
osx Dropbox.app                     || brew cask install dropbox
osx Hazel.prefPane                  || brew cask install hazel
osx DaisyDisk.app                   || brew cask install daisydisk
osx Disk Sensei.app                 || app Disk-Sensei/Disk-Sensei.dmg    
osx The Unarchiver.app              || brew cask install the-unarchiver

# utilities
osx 1Password 5.app                 || brew cask install onepassword
osx Bartender 2.app                 || brew cask install bartender
osx Keyboard Maestro.app            || brew cask install keyboard-maestro
osx teleport.prefPane               || brew cask install teleport
osx Karabiner.app                   || brew cask install karabiner
osx TG Pro.app                      || brew cask install tg-pro
osx Flux.app                        || brew cask install flux
osx Viscosity.app                   || brew cask install viscosity
osx Lingon X.app                    || brew cask install lingon-x
osx Moom.app                        || brew cask install moom
osx Cocktail.app                    || brew cask install cocktail
osx GeekTool.app                    || brew cask install geektool
osx Little Snitch Configuration.app || brew cask install little-snitch
osx MadCatzRAT.prefPane             || app Mad-Catz-RAT/Mad-Catz-RAT-Driver.pkg 
osx ScreenDimmer.app                || app screendimmer/id562058942
osx RemoteMapper.app:               || app Remote-Mapper/RemoteMapper.zip

# sound
osx Soundflowerbed.app              || brew cask install soundflower
osx Audio Hijack.app                || brew cask install audio-hijack
osx Fission.app                     || brew cask install fission

# text
osx Scrivener.app                   || brew cask install scrivener
osx Aeon Timeline.app               || app Aeon-Timeline/AeonTimeline.dmg  
osx Marked 2.app                    || brew cask install marked
osx Microsoft Word.app              || app Microsoft-Office/MicrosoftOffice2011.dmg

# downloads
osx Newshosting.app                 || app Newshosting/Newshosting.dmg
osx Transmission.app                || brew cask install transmission
osx YouTube to MP3.app              || brew cask install fourk-youtube-to-mp3
osx YouTube Downloader.app          || brew install youtube-dl

# video
osx VLC.app                         || brew cask install vlc
osx HandBrake.app                   || brew cask install handbrake
osx Plex Home Theater.app           || brew cask install plex-home-theater
osx AirParrot 2.app                 || brew cask install airparrot
osx AirServer.app                   || brew cask install airserver
osx Final Cut Pro.app               || app final-cut-pro/id424389933
osx Lock \& Load.fxplug             || app CoreMelt/CoreMeltLockAndLoad.dmg
osx Fisheye Removal Plugin.moef     || app FCPeffects/Fisheye-Removal-Plugin-Installer.pkg
osx CreateDiskImage.app             || app CreateDiskImage/CreateDiskImage.dmg
osx GoPro Studio.app                || brew cask install gopro-studio

# music
osx cmus                            || brew install cmus
osx Groovesquid.app                 || brew cask install groovesquid
osx Spotify.app                     || brew cask install spotify
osx Spotify Notifications.app       || brew cask install spotify-notifications

# communication
osx Telegram.app                    || brew cask install telegram
osx Skype.app                       || brew cask install skype
osx GoogleTalkBrowserPlugin.plugin  || brew cask install google-hangouts
osx Slack.app                       || brew cask install slack
osx centerim                        || brew install center-im
osx mutt                            || brew install mutt

# games
osx Steam.app                       || brew cask install steam
osx Dolphin.app                     || brew cask install dolphin
osx Steam.app                       || brew cask install controllermate

# quicklook plugins
osx QLColorCode.qlgenerator         || brew cask install qlcolorcode
osx QLMarkdown.qlgenerator          || brew cask install qlmarkdown
osx QLStephen.qlgenerator           || brew cask install qlstephen
osx QuickLookJSON.qlgenerator       || brew cask install quicklook-json

# all done
brew cleanup
brew cask cleanup
