#!/bin/sh

brew update
brew upgrade

# homebrew taps
brew tap homebrew/dupes
brew tap homebrew/versions
brew tap homebrew/homebrew-php
brew tap thoughtbot/formulae
brew tap suderman/suds
brew tap phinze/cask 
brew tap caskroom/versions 
brew tap caskroom/fonts

# homebrew external commands
brew install brew-cask

# dependencies
brew cask install xquartz
brew install ctags-exuberant
brew install cscope

# languages
brew install ruby
brew install chruby
brew install ruby-install
brew install nginx
brew install php55 --with-mysql --with-cgi
brew install lua
brew install luajit
brew install python
brew cask install node

# databases
brew install redis
brew install mongodb
brew install sqlite
brew install mysql
brew cask install sequel-pro  

# git
brew install git
brew install tig
brew install gitsh
brew cask install gitbox

# shell
brew cask install iterm2
brew install tmux
brew install wemux
brew install rcm
brew install direnv
brew install mobile-shell

# shell apps
brew install mackup
brew install ssh-copy-id
brew install autojump
brew install ranger
brew install highlight
brew install wget
brew install dockutil
brew install fswatch
brew install duti

# virtual machine
brew cask install vmware-fusion
brew cask install virtualbox
brew cask install vagrant
brew install docker
brew install packer
brew install ec2-api-tools

# dev apps
brew install vim --with-client-server --with-lua --with-luajit
brew install fzf
brew install ack
brew install ag
brew cask install heroku-toolbelt
brew cask install kaleidoscope
brew install imagemagick --build-from-source
brew install fontforge
brew cask install transmit
brew cask install integrity

# browsers
brew cask install firefoxdeveloperedition
brew cask install google-chrome-canary
brew cask install fluid
brew cask install choosy
brew cask install flash-player
brew cask install silverlight
brew install w3m

# utilities
brew cask install owncloud
brew cask install bittorrent-sync
brew cask install dropbox
brew cask install onepassword
brew cask install bartender
brew cask install keyboard-maestro
brew cask install teleport
brew cask install daisydisk
brew cask install the-unarchiver
brew cask install karabiner
brew cask install hazel
brew cask install tg-pro
brew cask install flux
brew cask install viscosity
brew cask install lingon-x
brew cask install moom
brew cask install cocktail
brew cask install geektool
brew cask install little-snitch


# sound
brew cask install soundflower
brew cask install audio-hijack
brew cask install fission

# text
brew cask install scrivener
brew cask install marked

# downloads
brew cask install transmission
brew cask install fourk-youtube-to-mp3
brew install youtube-dl

# video
brew cask install vlc
brew cask install handbrake
brew cask install air-video-server
brew cask install plex-home-theater
brew cask install airparrot
brew cask install airserver

# music
brew install cmus
brew cask install groovesquid
brew cask install spotify
brew cask install spotify-notifications

# communication
brew cask install telegram
brew cask install skype
brew cask install google-hangouts
brew cask install slack
brew install center-im
brew install mutt

# games
brew cask install steam
brew cask install dolphin
brew cask install controllermate

# quicklook plugins
brew cask install qlcolorcode
brew cask install qlmarkdown
brew cask install qlstephen
brew cask install quicklook-json

# all done
brew cleanup
brew cask cleanup

# missing from cask

osx /usr/local/bin/vim                 || brew install vim --with-client-server --with-lua --with-luajit
osx mutt                               || brew install mutt
osx GoogleTalkBrowserPlugin.plugin     || brew cask install google-hangouts
osx Xcode.app                          || app xcode/id497799835
osx Disk Sensei.app                    || app Disk-Sensei/Disk-Sensei.dmg    
osx Hazel.prefPane                     || app Hazel/Hazel.dmg               
osx teleport.prefPane                  || app Teleport/teleport.zip         
osx MockSMTP.app                       || app mocksmtp/id423535515          
osx ScreenDimmer.app                   || app screendimmer/id562058942
osx Aeon Timeline.app                  || app Aeon-Timeline/AeonTimeline.dmg  

app Mad-Catz-RAT/Mad-Catz-RAT-Driver.pkg 

# Microsoft Word.app:                    ncheogj7u0tqd2u/Office-2011.dmg
# Final Cut Pro.app:                     final-cut-pro/id424389933
# Lock & Load.fxplug:                    4zvvinm1hzwlrt2/CoreMeltLockAndLoad.dmg
# Fisheye Removal Plugin.moef:           ns2ax6aavom78wu/Fisheye-Removal-Plugin-Installer.pkg
# CreateDiskImage.app:                   86099zyohmu7fok/CreateDiskImage.dmg
# GoPro Studio.app:                      iik1ghu2h1afa3d/GoProStudio.dmg
# Newshosting.app:                       nbipmpq44f9q8fu/Newshosting.dmg
# RemoteMapper.app:                      tj82m71xw1btvmk/RemoteMapper.zip

